name: ESP Async TCP CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:

jobs:

  build-pio:
    name: PlatformIO on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
    - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3.5.0
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4.9.1
      with:
        python-version: '3.11'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Build Tests
      run: bash ./.github/scripts/on-push.sh 1 1
